### ISSUE TITLE
Error in post-command-hook (webkit-katex-render-update): (wrong-type-argument integer-or-marker-p nil)

### ISSUE THREAD

**Issue by duzaichuan** [fuxialexander/emacs-webkit-katex-render#4]
I use veshboo's xwidget webkit support emacs. My init.el:
(use-package webkit-katex-render
  :load-path "~/emacs-webkit-katex-render"
  :commands (webkit-katex-render-mode))

I enabled it in org-mode and moved the cursor on the latex fragment. No preview pops up and I got the above error.

And I use evil. Any suggestions?

Thank you!

**Comment by duzaichuan** [comment]
veshboo/emacs link https://github.com/veshboo/emacs

**Comment by duzaichuan** [comment]
In latex mode with error: Error in post-command-hook (webkit-katex-render-update): (search-failed "[^\\\\]\\(\\\\(\\|\\\\)\\|\\\\\\[\\|\\\\]\\)")

**Comment by fuxialexander** [comment]
Sorry for the late reply. It seems that you are not using the standard "\[ \]" notation for latex segment. Is that the case?
